---
- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo

  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      
    - name: Write copy index.html
      ansible.builtin.copy:
        content: "<h1> hello! Deepika from web server deployed by ansible  </h1>"
        dest: /var/www/html/index.html

